version: "3.3"
services:

  user-app:
    container_name: user-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      my_network:

  user-service:
    container_name: user-service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      my_network:

networks:
  my_network:
    external: false
    name: my-network


