# documentation can be found at: https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/
name: User App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  user_app_ci:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t user-app ./app
          docker build -t user-service ./user_service
          echo -n "verifying images:"
          docker images

      - name: Enable Ingress
        run: |
          minikube addons enable ingress

      - name: Deploy to minikube
        run: | 
          kubectl apply -f infrastructure/my_network-networkpolicy.yaml
          kubectl apply -f infrastructure/user-app-deployment.yaml
          kubectl apply -f infrastructure/user-app-service.yaml
          kubectl apply -f infrastructure/user-service-deployment.yaml
          kubectl apply -f infrastructure/user-service-service.yaml
          kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
          kubectl apply -f infrastructure/ingress.yaml

      - name: sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      - name: Test user-app
        uses: medyagh/setup-minikube@master
      - run: |
          echo "------------------wait for pods availability------------------"
          kubectl wait --for=condition=Ready pod/$user-app
          kubectl wait --for=condition=Ready pod/$user-service
          echo "------------------get pods------------------"
          kubectl get pods
          echo "------------------service list------------------"
          minikube service list
        env:
          user-app: (kubectl get pods --no-headers -o custom-columns=":metadata.name")[0]
          user-service: (kubectl get pods --no-headers -o custom-columns=":metadata.name")[1]
#          echo "------------------ingress-nginx url------------------"
#          minikube service ingress-nginx-controller -n ingress-nginx --url
#          echo "------------------opening the service------------------"
#          curl $(minikube service ingress-nginx-controller -n ingress-nginx --url)/login