name: User App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  user_app_ci:

    runs-on: self-hosted

    steps:

    - name: install dependencies
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

    - name: build
      uses: actions/checkout@v2
    - run: |
          docker network create my-network
          docker-compose up -d --build

    - name: prepare test environment
      uses: actions/setup-python@v2
    - run: |
          pip install pytest
          pip install requests

    - name: test
      run: pytest tests/backend_tests/

    - name: clean
      run: docker-compose down