name: User App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  user_app_ci:

    runs-on: ubuntu-latest

    steps:

    - name: build
      uses: actions/checkout@v2
    - run: |
          docker network create my-network
#          docker-compose up -d --build
#
#    - name: prepare test environment
#      uses: actions/setup-python@v2
#    - run: |
#          pip install pytest
#          pip install requests
#
#    - name: test
#      run: pytest tests/backend_tests/

    - name: Generate tag name
      run: echo "TAG_NAME=v$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create and push tag
      uses: git-actions/create-tag@v1.3
      with:
        tag: ${{ env.TAG_NAME }}
        message: "Release ${{ env.TAG_NAME }}"
        ref: "refs/tags/${{ env.TAG_NAME }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: clean
      run: docker-compose down