# documentation can be found at: https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/
name: User App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  user_app_ci:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t user-app ./app
          docker build -t user-service ./user_service
          echo -n "verifying images:"
          docker images

      - name: Deploy to minikube
        run: | 
          kubectl apply -f infrastructure/my_network-networkpolicy.yaml
          kubectl apply -f infrastructure/user-app-deployment.yaml
          kubectl apply -f infrastructure/user-app-service.yaml
          kubectl apply -f infrastructure/user-service-deployment.yaml
          kubectl apply -f infrastructure/user-service-service.yaml

      - name: Get pod name
        run: |
          pod_name=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" | grep user-app)
          echo "------------------pod name------------------"
          echo $pod_name
          echo "------------------pod name------------------"
          echo "::set-env name=POD_NAME::$pod_name"

      - name: Wait for pod to be ready
        run: |
          kubectl wait --for=condition=Ready pod/$POD_NAME -n default --timeout=60s
        env:
          POD_NAME: $ {{ env.POD_NAME }}

      - name: Port Forwarding
        run: |
          kubectl port-forward deployment/user-app 5000:5000 &
          PORT_FORWARD_PID=$!
          
      - name: prepare test environment
        uses: actions/setup-python@v2
      - run: |
            pip install pytest
            pip install requests

      - name: test
        run: pytest tests/backend_tests/

      - name: Kill port forward process
        run: |
          kill $PORT_FORWARD_PID