name: Create Git Tag

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'+%Y_%m_%d___%H_%M_%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Commit files
      env:
        COMMIT_MESSAGE: |
          git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git tag -a ${{ env.date }} -m $COMMIT_MESSAGE
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        tags: true
        branch: ${{ github.head_ref }}