name: User App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  user_app_ci:

    runs-on: ubuntu-latest

    steps:
    - name: build
    - uses: actions/checkout@v2
      run: docker-compose up -d --build

    - uses: actions/setup-python@v2
    - name: prepare test environment
      run: |
          pip install pytest
          pip install requests

    - name: test
      run: |
          pytest .\tests\backend_tests\
